name: CI pipeline

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
      with:
        python-version: 3.12.0

    - uses: iterative/setup-cml@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}

    - name: install dependencies
      run: 
        python test.py

    - name: Create CML report
      env:
        REPO_TOKEN: ${{ secrets.EAI_CONNECT }}

      run: |
        echo "# Report on Scoring metrics of model" >> report.md
        echo "## Bar Plot" >> report.md
        echo '![]()' >> report.md